name: IPAnalysisTool
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.13
  - graph-tool=2.84
  - psycopg2=2.9.9
  - sortedcontainers=2.4.0
  - pyyaml=6.0.2
  - pandas
  - jupyter
  - scikit-learn
  - statsmodels
  - pip
  - pip:
      - ipwhois