name: IPAnalysisTool
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - basemap=1.4.1
  - graph-tool=2.92
  - jupyter
  - maxminddb=2.6.2
  - pandas=2.2.3
  - pip
  - psycopg2
  - pyinstaller=5.13.2
  - pyproj=3.6.0
  - python=3.11
  - pyyaml
  - scikit-learn
  - sortedcontainers
  - statsmodels
  - pip:
      - ipwhois